class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror3'
        self.UnzipMirrorCommand = 'unzipmirror3'
        self.TarMirrorCommand = 'tarmirror3'
        self.ZipMirrorCommand = 'zipmirror3'
        self.CancelMirror = 'cancel3'
        self.CancelAllCommand = 'cancelall3'
        self.ListCommand = 'list'
        self.StatusCommand = 'status3'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'auth3'
        self.UnAuthorizeCommand = 'unauth3'
        self.AddSudoCommand = 'addsudo3'
        self.RmSudoCommand = 'rmsudo3'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart3'
        self.StatsCommand = 'stats3'
        self.HelpCommand = 'help3'
        self.LogCommand = 'log3'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone3'
        self.CountCommand = 'count3'
        self.WatchCommand = 'watch3'
        self.TarWatchCommand = 'tarwatch3'
        self.DeleteCommand = 'del3'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell3'
        self.UpdateCommand = 'update'
        self.ExecHelpCommand = 'exechelp3'
        self.TsHelpCommand = 'tshelp3'

BotCommands = _BotCommands()
